apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fcp-data-access-layer
  description: FCP Data Access Layer
spec:
  type: team
  profile:
    displayName: FCP Data Access Layer
    picture: https://avatars.githubusercontent.com/u/5528822?s=200&v=4
  parent: farming-countryside-programme
  children: []
