parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
pr:
  branches:
    include:
      - main
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA-ADP
      type: github
      ref: refs/tags/1.0.0-latest

extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    teamName: ${{ values.project_name | yaml | indent(6) }}
    serviceName: ${{ values.service_name | yaml | indent(6) }}
    deployFromFeature: {% raw %}${{ parameters.deployFromFeature }}{% endraw %}
    appBuildConfig:
      appFrameworkType: "helm"
      projectPath: "helm/${{values.service_name}}/Chart.yaml"
      imageRepoName: ${{ values.service_name | yaml | indent(8) }}

