services:
  ? ${{ values.service_name | yaml | indent(4) }}
  : command: npm run start:watch
    build:
      target: development
    image: ${{ (values.service_name + "-development") | yaml | indent(4) }}
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output:/home/node/test-output

  zap-baseline-scan:
    image: softwaresecurityproject/zap-bare:2.14.0
    command: zap.sh -cmd -quickurl http://${{ values.service_name | yaml | indent(4) }}:${PORT:-3000} -zapit http://${{ values.service_name | yaml | indent(4) }}:${PORT:-3000} -configfile config/zap.conf -quickout test-output/zap-report.html -silent -quickprogress
    depends_on:
      - ${{ values.service_name | yaml | indent(4) }}
    volumes:
      - ./test-output:/zap/test-output
      - ./zap:/zap/config
