services:
  ? ${{ values.service_name | yaml | indent(4) }}
  : build:
      context: .
      target: production
    image: ${{ values.service_name | yaml | indent(4) }}
    container_name: ${{ values.service_name | yaml | indent(4) }}
    environment:
      APPINSIGHTS_CLOUDROLE: ${{ (values.service_name + "-local") | yaml | indent(4) }}
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
