services:
  ${{ values.service_name }}:
    build:
      context: .
      target: production
    image: ${{ values.service_name }}
    container_name: ${{ values.service_name }}
    environment:
      APPINSIGHTS_CLOUDROLE: ${{ values.service_name }}-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
