# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? ${{ values.service_name | yaml | indent(4) }}
  : build:
      target: development
    image: ${{ (values.service_name + "-development") | yaml | indent(4) }}
    container_name: ${{ (values.service_name + "-development") | yaml | indent(4) }}
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
