apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: defra
  title: DEFRA
  description: UK government department responsible for safeguarding our natural environment, supporting our food & farming industry, and sustaining a thriving rural economy.
  links:
    - url: https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs/
      title: Website

spec:
  type: organization
  profile:
    displayName: DEFRA
    picture: https://avatars.githubusercontent.com/u/5528822?s=200&v=4
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: defra-delivery-programmes
  description: All delivery programmes within the Defra organization.
spec:
  targets:
    - ./delivery-programmes/apha-europe-trade.yaml
    - ./delivery-programmes/coreai.yaml
    - ./delivery-programmes/ea-extended-producer-responsibility.yaml
    - ./delivery-programmes/mmo-fisheries.yaml
    - ./delivery-programmes/ne-biodiversity-net-gains.yaml
    - ./delivery-programmes/rpa-farming-countryside-programme.yaml
    - ./delivery-programmes/rpa-legacy-applications-programme.yaml

