name: ${{ values.project_name }}
namespace: ${{ values.workstream }}
workstream: ${{ values.workstream }}
image: ${{ values.project_name }}

labels:
  component: web

container:
  memCpuTier: L

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
  
ingress:
  class: nginx
  endpoint: ${{ values.project_name }}
  server: ${{ values.project_name }}.{ENVIRONMENT}.adp.defra.gov.uk
