apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adp-empty-project-template
  title: ADP Empty Project Template
  description: Template to support rapid delivery of microservices for ADP Platform. It is used to scaffold an empty project (that only contains README.md, pull_request_template.md and catalog.yaml files).
  tags:
    - empty-project
    - repository
spec:
  owner: ccts-adp
  type: empty-project
  parameters:
    - $yaml: ./parameters.yaml
    - $yaml: ../parameters/git-repository.yaml
  steps:
    - $yaml: ./run-template.yaml
    - $yaml: ../steps/github-publish.yaml
    - $yaml: ../steps/github-team.yaml
    - $yaml: ../steps/catalog-register.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
