apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | yaml | indent(2) }}
  {% if values.description -%}
  description: ${{ values.description | yaml | indent(2) }}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{ values.repo_project_slug | yaml | indent(2) }}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: ${{ "https://github.com" | path(values.repo_project_slug) | yaml | indent(8) }}
      title: GitHub Repository
      icon: github

spec:
  type: ${{ values.component_type | yaml | indent(2) }}
  lifecycle: ${{ values.component_lifecycle | yaml | indent(2) }}
  owner: ${{ values.owner | yaml | indent(2) }}
  {% if values.system -%}
  system: ${{ values.system | yaml | indent(2) }}
  {%- endif %}
