apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adp-helm-only-template-dev
  title: ADP Helm Only Template DEV
  description: Deploy a HELM Only repository for micro-frontends and mergeable ingresses. This creates a HELM only repository with some basic configuration and a pipeline without any app code. This allows you to use a single URL for multiple different frontend repositories
  tags:
    - helm
spec:
  owner: ccts-adp
  type: helm
  parameters:
    - $yaml: ./parameters.yaml
    - $yaml: ../parameters/git-repository.yaml
    - $yaml: ../parameters/ci-cd.yaml
  steps:
    - $yaml: ./run-template.yaml
    - id: publish
      name: Publish
      action: publish:zip

  output:
    links:
      - title: Download
        url: ${{ steps.publish.output.dataUri }}
        icon: github
