services:
  ${{ values.service_name }}:
    build:
      context: .
      target: production
    image: ${{ values.service_name }}
    container_name: ${{ values.service_name }}
    depends_on:
      - ${{ values.service_name }}-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ${{ values.service_name }}-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  ${{ values.service_name }}-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ${{ values.service_name }}
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
