# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ? ${{ values.service_name | yaml | indent(4) }}
  : build:
      target: development
    image: ${{ (values.service_name + "-development") | yaml | indent(4) }}
    container_name: ${{ (values.service_name + "-test") | yaml | indent(4) }}
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
